// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfMyhwjxIS96mVVbYuyyuEreZvBJwfpDY',
    appId: '1:837376398461:web:18c5c2528eecac79ca4d14',
    messagingSenderId: '837376398461',
    projectId: 'authentication-68ce1',
    authDomain: 'authentication-68ce1.firebaseapp.com',
    storageBucket: 'authentication-68ce1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEIJ5Z9JaInEtShY4OEXhlWu4ODvdJTyc',
    appId: '1:837376398461:android:d66fd508165a2c87ca4d14',
    messagingSenderId: '837376398461',
    projectId: 'authentication-68ce1',
    storageBucket: 'authentication-68ce1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAA9gDHSor8Z3IPPgzBr07qa2MI0UG20fc',
    appId: '1:837376398461:ios:54b996e2f59b615dca4d14',
    messagingSenderId: '837376398461',
    projectId: 'authentication-68ce1',
    storageBucket: 'authentication-68ce1.appspot.com',
    iosClientId: '837376398461-7ilnphfbhj9so2v90504fub2ifel9eru.apps.googleusercontent.com',
    iosBundleId: 'com.example.modernlogintute',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAA9gDHSor8Z3IPPgzBr07qa2MI0UG20fc',
    appId: '1:837376398461:ios:54b996e2f59b615dca4d14',
    messagingSenderId: '837376398461',
    projectId: 'authentication-68ce1',
    storageBucket: 'authentication-68ce1.appspot.com',
    iosClientId: '837376398461-7ilnphfbhj9so2v90504fub2ifel9eru.apps.googleusercontent.com',
    iosBundleId: 'com.example.modernlogintute',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAfMyhwjxIS96mVVbYuyyuEreZvBJwfpDY',
    appId: '1:837376398461:web:6f8205ffb995171cca4d14',
    messagingSenderId: '837376398461',
    projectId: 'authentication-68ce1',
    authDomain: 'authentication-68ce1.firebaseapp.com',
    storageBucket: 'authentication-68ce1.appspot.com',
  );
}
